import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import ym from 'react-yandex-metrika';
// инициализируем код метрики, чтобы библиотека встроила метрику в приложение
import { YMInitializer } from 'react-yandex-metrika';


export default function App({ Component, pageProps, router }: AppProps): JSX.Element {
  //подписываемся на изменение роута и при каждом изменении роута отправляем в метрику событие hit
  router.events.on('routeChangeComplete', (url: string) => {
    //проверяем, что мы не на сервере, а на клиенте
    if (typeof window !== 'undefined') {
      ym('hit', url);
    }
  });

  return <>
    <Head>
      <title>Тайтл проекта</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
      <meta property='og:locale' content="ru_RU" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link rel="preconnect" href="https://mc.yandex.ru" />
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;700&display=swap" rel="stylesheet" />
    </Head>
    <YMInitializer 
      accounts={[]} //указываем номера необходимых яндекс счетчиков
      options={{ webvisor: true, defer: true }}
      version='2'
    />
    <Component {...pageProps} />
  </>;
}
